authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as v
# from django.contrib.auth import login

app_name = "auth"
urlpatterns = [
    path('', views.home, name="home"),
    path('home', views.home, name="home"),
    path('login', v.LoginView.as_view(), name='login'),
    path('logout', v.LogoutView.as_view(), name="logout"),
    path('sign-up', views.sign_up, name="sign-up")
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("authentication.urls")),
    path('', include('django.contrib.auth.urls')),
    path('post/', include('posts_and_comments.urls')),
    path('admin/', admin.site.urls),
]

posts_and_comments/urls.py
from django.urls import path
from . import views 

app_name = 'post'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('create_post', views.create_post, name = 'create_post')
]

authentication/models.py
from django.db import models

# Create your models here.

posts_and_comments/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + " :\n" + self.description 

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

posts_and_comments/forms.py
from django import forms
from .models import Post


class PostingForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description"]

authentication/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import RegistrationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/login')
def home(request):
    return render(request, "authentication/home.html")

# def login_user(request):
#     if request.method == "POST":
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             return redirect(reverse('auth:home'))
#         else:
#             return redirect(reverse("auth:login"))
        
    # return render(request, "registration/login.html")

def sign_up(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('auth:home'),)
    else:
        form = RegistrationForm()

    return render(request, "registration/sign-up.html", {"form": form})

posts_and_comments/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import Post
from django.contrib.auth.models import User, Group
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostingForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required

# Create your views here.
@login_required(login_url='/login/?next=/post')
def index(request):
    latest_post_list = Post.objects.all().order_by("-created_at")[:10]
    
    if request.method == "POST":
        post_id = request.POST.get("post_id")
        user_id = request.POST.get("user_id")
        if post_id:
            post = Post.objects.get(id = post_id)
            if post and (post.author == request.user or request.user.has_perm("posts_and_comments.delete_post")):
                post.delete()
        elif user_id:
            user = User.objects.get(id=user_id)
            print(user)
            if user and request.user.is_staff:
                group = Group.objects.get(name='default')
                group.user_set.remove(user)

                group = Group.objects.get(name='mod')
                group.user_set.remove(user)

    return render(request, "posts_and_comments/index.html", {'latest_post_list' : latest_post_list})

# class IndexView(LoginRequiredMixin, generic.ListView):
#     template_name = "posts_and_comments/index.html"
#     context_object_name = "latest_post_list"
#     login_url = "/login/?next=/post"

#     def get_queryset(self):
#         """
#             Return the last ten published questions and the last comment on that post.
#         """

#         return Post.objects.all().order_by("-created_at")[:10]

@permission_required("posts_and_comments.add_post", login_url="/login", raise_exception=True)
def create_post(request):
    if request.method == 'POST':
        form = PostingForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(reverse('post:index'))
    else:
        form = PostingForm()

    return render(request, "posts_and_comments/create_post.html", {"form": form})

    

authentication/templates/authentication/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Website{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>

<body>
    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-dar bg-dark">
            <div class="container-fluid">
                <div>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'auth:home'%}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="/post">Post</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                            <span class="navbar-text text-light">Logged in as {{user.username}} | </span>
                            <li class="nav-item">
                                <a class="nav-link text-light" href="/logout">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link text-light" href="{% url 'auth:login'%}">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>

            </div>
        </nav>
    {% endblock navbar %}
    <div class="container">{% block content %}{% endblock content %}</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>

</html>

authentication/templates/authentication/home.html
{% extends 'authentication/base.html' %}

{% block title%}Home page{% endblock %}
{% block content %}<h1>Home page!{% endblock %}

posts_and_comments/templates/posts_and_comments/create_post.html
{% extends 'authentication/base.html' %}
{% block title%}Create a post{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" action = "{% url 'post:create_post' %}">
        {% csrf_token %}{{form|crispy}}
        <button type = "submit" class="btn btn-success">Post</button>
    </form>
{% endblock content %}

posts_and_comments/templates/posts_and_comments/index.html
{% extends 'authentication/base.html' %}

{% block title%}Home page{% endblock %}
{% block content %}
    <div class="container-fluid">
        <button type="button" class="btn btn-light"><a href="{% url 'post:create_post' %}">Create new post</a></button>
    </div>
    {% for post in latest_post_list %}
        <div class="card mt-2">
            <div class="card-header"><strong>@{{ post.author }}</strong></div>
            <div class="card-body d-flex flex-row justify-content-between">
                <div>
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p>{{ post.description }}</p>
                </div>
                <div>
                    {% if user == post.author or perms.posts_and_comments.delete_post %}
                        <form method="post">
                            {% csrf_token %}
                            <button type = "submit" class = "btn btn-danger" name = "post_id" value="{{ post.id }}">Delete</button>
                        </form>
                    {% endif %}
                    {% if user.is_staff %}
                        <form method="post">
                            {% csrf_token %}
                            <button type = "submit" class = "btn btn-warning" name = "user_id" value = "{{ post.author.id }}">Ban user</button>
                        </form>   
                    {% endif %}
                </div>
            </div>
            <div class="card-footer text-muted">{{ post.created_at }}</div>
        </div>
        {% empty %}
            <p>No posts available</p>
    {% endfor %}
{% endblock content %}